### ISSUE TITLE
Map reject-with icmp-proto-unreachable with ipv6

### ISSUE THREAD

**Issue by mfinelli** [MaxKellermann/ferm#10]
REJECT reject-with icmp-proto-unreachable is valid ipv4, but not ipv6

ipv4:
```
root@host:~# iptables -j REJECT -h | grep "Valid reject types" -A 17
Valid reject types:
    icmp-net-unreachable     	ICMP network unreachable
    net-unreach              	alias
    icmp-host-unreachable    	ICMP host unreachable
    host-unreach             	alias
    icmp-proto-unreachable   	ICMP protocol unreachable
    proto-unreach            	alias
    icmp-port-unreachable    	ICMP port unreachable (default)
    port-unreach             	alias
    icmp-net-prohibited      	ICMP network prohibited
    net-prohib               	alias
    icmp-host-prohibited     	ICMP host prohibited
    host-prohib              	alias
    tcp-reset                	TCP RST packet
    tcp-rst                  	alias
    icmp-admin-prohibited    	ICMP administratively prohibited (*)
    admin-prohib             	alias
```

ipv6:
```
root@host:~# ip6tables -j REJECT -h | grep "Valid reject types" -A 11
Valid reject types:
    icmp6-no-route           	ICMPv6 no route
    no-route                 	alias
    icmp6-adm-prohibited     	ICMPv6 administratively prohibited
    adm-prohibited           	alias
    icmp6-addr-unreachable   	ICMPv6 address unreachable
    addr-unreach             	alias
    icmp6-port-unreachable   	ICMPv6 port unreachable
    port-unreach             	alias
    tcp-reset                	TCP RST packet
    tcp-reset                	alias
```

Using reject-with icmp-proto-unreachable in a block shared by both `ip` and `ip6` causes an error

```
root@host:/etc/ferm# ferm ferm.conf 
ip6tables-restore v1.4.21: unknown reject type "icmp6-proto-unreachable"
Error occurred at line: 16
Try `ip6tables-restore -h' or 'ip6tables-restore --help' for more information.
Failed to run /sbin/ip6tables-restore

Firewall rules rolled back.
```

This means the configuration that could otherwise be combined due to the mapping that ferm already does doesn't work and the configuration has to be duplicated.

Is it possible to have ferm automatically drop icmp-proto-unreachable when the domain is ip6 so that we can keep the configuration the same?

(According to this: https://www.toofishes.net/blog/making-things-ipv6-capable/ we can just drop the reject-with override)

**Comment by MaxKellermann** [comment]
It is unfortunate that you can't use the same rules for IPv6 if you explicitly use IPv4-only features. But ferm is not the right place to fix this up. You may want ferm to just ignore that feature, but others (including me) disagree. Those who disagree are right: why would ferm silently ignore an explicit user request? If your rules contain mistakes (such as asking ferm to use a non-existent feature), then this mistake should result in an error message, not in ferm silently dropping the rule.

**Comment by mfinelli** [comment]
That's fair. I'll comment my workaround here for other people who stumble upon this issue.

```
@if @eq($DOMAIN, ip6) {
    REJECT;
} @else {
    REJECT reject-with icmp-proto-unreachable;
}```
