### ISSUE TITLE
New option 'ferm --flush-all' ?

### ISSUE THREAD

**Issue by github-user-1** [MaxKellermann/ferm#11]
First of all thanks and congratulations to the ferm-tool - it comes in very handy and is very useful; keep up with the great work!

One (rather minor) option I'm missing from time to time when starting from scratch would be a simple `ferm --flush-all` (without a config file provided) to remove any rules although I don't have a ferm.conf file at hand.

Maybe, I'm overlooking some reasoning against something like this, but at the moment I thought it would be a nice-to-have option :-)

**Comment by nwoodthorpe-test1** [comment]
❤️ 💚 💙 💛 💜![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f5a4.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f499.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f494.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f491.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f468-2764-1f468.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f491.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f469-2764-1f469.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49d.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49a.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2764.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49f.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f60d.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f63b.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f493.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f497.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2665.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/2763.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f618.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49c.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49e.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f496.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f495.png?v7 "Logo Title Text 1")![alt text](https://assets-cdn.github.com/images/icons/emoji/unicode/1f49b.png?v7 "Logo Title Text 1")Seen by Nathaniel Woodthorpe at 00:05

**Comment by MaxKellermann** [comment]
There's already `iptables -F`, what's wrong with that?
Without a configuration file, how can ferm know which domains/tables to flush? What policy shall be used?
