### ISSUE TITLE
Allow symbolic links on include

### ISSUE THREAD

**Issue by bernhardschmidt** [MaxKellermann/ferm#12]
We're thinking of providing our users a default modular ferm ruleset that can be adjusted to their wishes, but updated by us as well. For this we were thinking about shipping files in a directory with a package (rules) and symlink them from another directory that gets included by ferm.conf, similar to conf-available/conf-enabled in Apache.

Unfortunately the code at https://github.com/MaxKellermann/ferm/blob/master/src/ferm#L965 currently checks whether the file is a regular file. Maybe something like this could be implemented?

```
                push @ret, $filename
                  if -f $filename || (-l $filename && -f readlink($filename));
```

**Comment by MaxKellermann** [comment]
Why do you believe such a change is necessary? `-f` follows symlinks, doesn't it?

**Comment by bernhardschmidt** [comment]
Damn you're right, I somehow messed up my testing. Sorry for the noise.
