### ISSUE TITLE
import-ferm failing

### ISSUE THREAD

**Issue by xavier83** [MaxKellermann/ferm#16]
I ran `sudo import-ferm` to convert my currrent firewall settings to ferm. It spewed several lines and stopped at `'option 'f' in line 99 not understood'`. seems like something went wrong. the existing firewalls rules were generated by [Arno's firewall](https://github.com/arno-iptables-firewall/aif)

**Comment by MaxKellermann** [comment]
It is impossible to reproduce your problem without an example file which reproduces this issue.

**Comment by xavier83** [comment]
fair-enough 😉  my iptables-save file is [here](https://gist.github.com/xavier83/31b70b044ad9028b4c8083a020544958)

**Comment by xavier83** [comment]
Woah that was fast. I even _backported_ your fix and it works like a charm. btw thanks for this cool project!
