### ISSUE TITLE
Add chain name length checking

### ISSUE THREAD

**Issue by jhendryUK** [MaxKellermann/ferm#21]
It appears the maximum chain name has been 28 chars since 2010 (  https://git.netfilter.org/iptables/log/?qt=grep&q=chain+name+length )

When trying to load a firewall with a name that is too long I get this:

jhendry@twigz ~/svn/cfengine/cf3/configroot/platform/firewall/devel/ng/ $ sudo iptables-restore < t
iptables-restore v1.6.0: Invalid chain name `DROP_RFC1918_BROADCAST_AND_MCAST' (28 chars max)
Error occurred at line: 11
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

Can we add checking of chain name length to ferm?

**Comment by jhendryUK** [comment]
The error from IPTables stats 28 characters but after testing on Ubuntu 16.04 I have a 29 character limit (which is consistent with the details in the link in my OP).

Made the limit 29 characters in my PR

**Comment by MaxKellermann** [comment]
53d4d8cf3226871d74c6a5816dffa7cec144cce4
