### ISSUE TITLE
Two "--match-set"  in same rule doesn't work properly

### ISSUE THREAD

**Issue by fedoroff** [MaxKellermann/ferm#22]
E.g., we have rule like that:
`mod set set front-srvs src mod set set back-srvs dst ACCEPT;`
Ferm converts it into such a rule for iptables:
`-A FORWARD --match set --match-set front-srvs src --match-set back-srvs dst --jump ACCEPT`
And iptables give an error:
`iptables-restore v1.6.0: --match-set can be specified only once`
Because right rule should look like this:
`-A FORWARD -m set --match-set front-srvs src -m set --match-set back-srvs dst -j ACCEPT`
Somewhere lost second "-m set".

**Comment by MaxKellermann** [comment]
You can load the same match module twice? The manpage does not suggest that - do you have any documentation pointer explaining this?

**Comment by fedoroff** [comment]
Yep, i can and this work fine. Look at here for example:
https://utcc.utoronto.ca/~cks/space/blog/linux/IptablesIpsetsMultipleMatches

**Comment by MaxKellermann** [comment]
Interesting, but this is just one random guy's blog. Is there official documentation on it? Without documentation, this may be an implementation detail which may disappear any time.

**Comment by fedoroff** [comment]
Hmm, i will search for more info.

**Comment by jhendryUK** [comment]
http://ipset.netfilter.org/iptables-extensions.man.html

Looks like this is a valid/supported way of writing riles.

Snippet: "You can specify multiple extended match modules in one line"

Sorry for the brief response, sending from my phone on a train.

**Comment by MaxKellermann** [comment]
I know that sentence, but it does not imply that you can load one module twice. I believe that you are right, and this is a "supported" case, but it's undocumented (and surprising, at least to me).

**Comment by jhendryUK** [comment]
I will follow up with a query to the netfilter dev team. They have been quick to respond to quieries I have raised recently, it should not take took long.

**Comment by MaxKellermann** [comment]
@jhendryUK did you meanwhile get a clarification?

**Comment by MaxKellermann** [comment]
Closing after more than two years without a reply.
