### ISSUE TITLE
@resolve of IP should return IP

### ISSUE THREAD

**Issue by hudecof** [MaxKellermann/ferm#3]
Hi,

this might be more **feature request** as an issue.

Would it be possible to return or `@resolve` IP address if the input is IP address?
```
  if type == 'A' and address is IPv4:
      return address
  if type == 'AAAA' and address is IPv6:
      return address
```

**Comment by MaxKellermann** [comment]
Why?

**Comment by hudecof** [comment]
my rules are generated by configuation managment.
For some services where is possibility to put there IP or hostname or mix it. Using these variables I generate rules so the variable could be like

`@def $SERVICE_SERVERS=(srv01.example.com 192.168.100.34 ::1)`

The `resolve` function failes for IP address value.
```
domain $FERM_DOMAINS table filter chain INPUT {
    interface $IF_MNGT proto tcp dport $SERVICE_PORT subchain "IN-SERVICE-CLIENT" {
        saddr (@ipfilter($HOST_SERVICE_SERVERS)) ACCEPT;  #works only for IP addresses
#        saddr (@ipfilter(@resolve($HOST_SERVICE_SERVERS, A))) ACCEPT;
#        saddr (@ipfilter(@resolve($HOST_SERVICE_SERVERS, AAAA))) ACCEPT;
    }
}
```

resolving could by done by **iptables** itselfs or by **ferm**. I preffer **ferm**.

I'm trying to figure out, if itcould be done by configuration managment itself.

**Comment by MaxKellermann** [comment]
Certainly, one should avoid resolving "at runtime"; i.e. depending on DNS being available and functional while the firewall is configured.

Anyway, implemented.  562c810c8ce400378b4c2edd2dee6e7beb6757d6

**Comment by hudecof** [comment]
Thanks.
I known, that resolving at runtime is bad ;(
