### ISSUE TITLE
[Feature request] Are you considering make Ferm a wrapper to nftables?

### ISSUE THREAD

**Issue by q2dg** [MaxKellermann/ferm#30]
It seems to be the future instead of iptables
Thanks!

**Comment by MaxKellermann** [comment]
Why? nftables imitates the ferm syntax, obsoleting ferm. What would be left to do for ferm?

**Comment by q2dg** [comment]
Ah,..mmm...yes, yes, you're right. It wa a silly idea. Ferm future is bound to iptables future, period.
Ok, thanks for your fast answer!
I close the issue
