### ISSUE TITLE
multiport shortcuts

### ISSUE THREAD

**Issue by 532910** [MaxKellermann/ferm#33]
What do you think about shortcuts for mod multiport:
sports -> mod multiport source-ports
dports -> mod multiport destination-ports
?

**Comment by jhendryUK** [comment]
I think this is a great idea, can we do it for 'comment' and 'state' as well?  I am happy to spend some time of this if it will eventually be accepted

**Comment by c-e-p-x-u-o** [comment]
The workaround:

```
@def &dports() =
	mod multiport destination-ports;
@def &sports() =
	mod multiport source-ports;
```

**Comment by 532910** [comment]
Thank you! (:

**Comment by 532910** [comment]
Will it work for ip6 or for ip only?
