### ISSUE TITLE
v2.5 released or not?

### ISSUE THREAD

**Issue by 532910** [MaxKellermann/ferm#51]
http://ferm.foo-projects.org/download/2.5/NEWS
v2.5 - not yet released

**Comment by 532910** [comment]
1. http://ferm.foo-projects.org/download/2.5/NEWS
still not updated

2. it's a pity that such a minor issues takes so long time.

**Comment by MaxKellermann** [comment]
>     1. http://ferm.foo-projects.org/download/2.5/NEWS
>        still not updated

I can't travel back in time.

>     2. it's a pity that such a minor issues takes so long time.

You named the reason already: it's such a minor issue. It doesn't affect anything, it doesn't affect how ferm works. It has no priority. It's good to fix it, it's good that you reported it, but there's no hurry at all.

Save your mourning for real bugs.
