### ISSUE TITLE
broute table is not flushed

### ISSUE THREAD

**Issue by 532910** [MaxKellermann/ferm#52]
Steps to reproduce:

1. clear broute table:
```
# ebtables -t broute -F
# s ebtables -t broute -L
Bridge table: broute

Bridge chain: BROUTING, entries: 0, policy: ACCEPT
```
2. update ferm configuration, add:
```
domain eb table broute chain BROUTING {
    daddr $PrinterMAC DROP;
}
```
and restart ferm, rule will appear, as expected:
```
# ebtables -t broute -L      
Bridge table: broute

Bridge chain: BROUTING, entries: 1, policy: ACCEPT
-d PrinterMAC -j DROP 
```

3. undo step `2` and restart ferm, the rule will remain:

```
# ebtables -t broute -L      
Bridge table: broute

Bridge chain: BROUTING, entries: 1, policy: ACCEPT
-d PrinterMAC -j DROP 
```

**Comment by MaxKellermann** [comment]
That's because ferm will only touch tables which are mentioned in the configuration.

**Comment by 532910** [comment]
> That's because ferm will only touch tables which are mentioned in the configuration.

It is not true!

switching from
`table filter chain INPUT proto tcp dport ssh ACCEPT;`
to
`table nat chain PREROUTING proto tcp DNAT daddr 10.11.11.8 dport 10 to 10.11.11.2;`
will **remove** ssh rure even `filter` table is not described more.
