### ISSUE TITLE
Wrong proto gives wrong error

### ISSUE THREAD

**Issue by 532910** [MaxKellermann/ferm#57]
```
% cat test.conf                            
domain eb table broute chain BROUTING {
  proto IPV4 op-source IP ACCEPT;
}

% /usr/sbin/ferm --remote test.conf       
ebtables --atomic-file /tmp/ferm.6kouSFtJQQ --atomic-save
Error in test.conf line 2:
domain eb table broute chain BROUTING 
{ 
    proto IPV4 op-source <--
Unrecognized keyword: op-source
zsh: exit 25    /usr/sbin/ferm --remote test.conf
```

It's hard to find the mistake (`IPV4` instead of `IPv4`) in the example above due to the wrong error `Unrecognized keyword: op-source`.

**Comment by MaxKellermann** [comment]
What is wrong with this error?

**Comment by 532910** [comment]
It says that `op-source` is unrecognized keyword, but it is correct.

**Comment by MaxKellermann** [comment]
It is not correct (in this context). Keywords are made known to ferm depending on the context. In this context, it's not a correct keyword.

**Comment by 532910** [comment]
What is context in this case? If the context is `IPV4` so incorrect the context itself, not the op-source keyword.

Anyway, the real error in the example is `IPV4` and not `op-source` so the error message should be about `IPV4` and not `op-source`, do you disagree?

**Comment by MaxKellermann** [comment]
ferm does not validate the `proto` parameter, because it does not validate any parameter. If it would do that, it would fail every time the kernel adds support for a new protocol.
So how should ferm know that `IPV4` is wrong?

**Comment by 532910** [comment]
but it knows that `IPv4` is valid in `eb`:
https://github.com/MaxKellermann/ferm/blob/bde1f876ee16cf2c44232e543661cbadc8f3c014/src/ferm#L378
so `IPV4` should be invalid, isn't it?

**Comment by MaxKellermann** [comment]
Your example sounds reasonable, but that's a subjective measure. You did not suggest an objective way for ferm to validate the parameter.
