### ISSUE TITLE
mod helper issue

### ISSUE THREAD

**Issue by jpiron** [MaxKellermann/ferm#62]
Hi,

I am trying to use the sane helper module to configure my firewall to allow access to a scanner.
Here is the Ferm configuration I use:
```
domain ip {
  table raw {
    chain PREROUTING {
      saddr $TRUSTED_NETWORKS proto tcp mod helper helper sane CT;
    }
  }
}
```
that produces the following iptable entry:
```
~# iptables -L -nv -t raw
Chain PREROUTING (policy ACCEPT 112 packets, 15721 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 CT         tcp  --  *      *       0.0.0.0/0             0.0.0.0/0            helper match "sane" CT
```
Unfortunately it doesn' work (as we can see with the `pkts` and `bytes` counters).

However, if I use the following raw iptables command : `iptables -t raw -A PREROUTING -p tcp -j CT --helper sane` that produces the following entry:
```
~# iptables -L -nv -t raw
Chain PREROUTING (policy ACCEPT 7 packets, 488 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    7   488 CT         tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            CT helper sane
```
it does work.

Am I missing something in the use of the helper module with Ferm ?

I am using Ferm 2.5.1 on Ubuntu 16.04.6(kernel 4.15.0-76-generic).

**Comment by MaxKellermann** [comment]
Your ferm config uses the `helper` match module, and your raw iptables command uses the `--helper` parameter for the `CT` target. These are two very different things.
What you probably meant to write was:
```
saddr $TRUSTED_NETWORKS proto tcp CT helper sane;
```

**Comment by jpiron** [comment]
Oh thank you and sorry for this non relevant issue.
