### ISSUE TITLE
Use @subchain without rule ?

### ISSUE THREAD

**Issue by tst2005** [MaxKellermann/ferm#67]
I like the `@subchain` feature to define and use a chain on-the-fly.

I'm trying to setup a whitelist for both IPv4 and IPv6, but I reached a limitation(?) of ferm about the `@subchain` feature.
I wonder if there is a better way than my workaround.

My goal (that is seems not possible) is:
```
@def $whitelist_direct    = `echo 1.2.3.4; echo 1:2:3:4:5:6:0/64`;

domain (ip ip6) table filter chain INPUT {
        @subchain ["whitelistcheck"] {
                saddr @ipfilter( ( $whitelist_direct ) ) @subchain ["whitelistaccept"] {
                        LOG log-prefix 'FW:whitelist: ';
                        ACCEPT;
                }
        }
}
```

My current workaround :
```
@def $whitelist_direct    = `echo 1.2.3.4; echo 1:2:3:4:5:6:0/64`;

domain (ip ip6) table filter chain INPUT {
        saddr @ipfilter( ( 0.0.0.0/0 ::0/0 ) )
        @subchain ["whitelistcheck"] {
                saddr @ipfilter( ( $whitelist_direct ) ) @subchain ["whitelistaccept"] {
                        LOG log-prefix 'FW:whitelist: ';
                        ACCEPT;
                }
        }
}
```

Is there a better way ?

**Comment by tst2005** [comment]
I found another workaround.
```
@def $whitelist_direct    = `echo 1.2.3.4; echo 1:2:3:4:5:6:0/64`;

domain (ip ip6) table filter chain INPUT {
        protocol all
        @subchain ["whitelistcheck"] {
                saddr @ipfilter( ( $whitelist_direct ) ) @subchain ["whitelistaccept"] {
                        LOG log-prefix 'FW:whitelist: ';
                        ACCEPT;
                }
        }
}
```

I wonder if there is a way generate a simple `-A INPUT --jump whitelistcheck`.

**Comment by MaxKellermann** [comment]
Just use `chain` instead of `@subchain`!

**Comment by tst2005** [comment]
Sorry for delay...

The main difference between `chain` and `@subchain` is to be able to use "automagically naming".
Yes, In this sample, I can use `chain` instead of `@subchain` (even I must also add a `jump whitelistcheck`).

```
@def $whitelist_direct    = `echo 1.2.3.4; echo 1:2:3:4:5:6::1`;

domain (ip ip6) table filter chain INPUT {
        chain ferm_manual_1 {
                saddr @ipfilter( ( $whitelist_direct ) ) @subchain {
                        LOG log-prefix 'FW:whitelist: ';
                        ACCEPT;
                }
        }
       jump ferm_manual_1;
}
```

but my dreams is more like :

```
@def $whitelist_direct    = `echo 1.2.3.4; echo 1:2:3:4:5:6::1`;

domain (ip ip6) table filter chain INPUT @subchain {
                saddr @ipfilter( ( $whitelist_direct ) ) @subchain {
                        LOG log-prefix 'FW:whitelist: ';
                        ACCEPT;
                }
}
```

because I'm working on migration (from current firewall setup) to ferm.
My goal is to produce a ferm config that generate the closest result than then original firewall rules dump.
I think it is not possible (not easy) to have a @subchain without `protocol ...` prefix.
I can workaround by adding a `protocol all` before `@subchain` and fix the result with a `sed s/--protocol all//g`

Thanks for all your work!
