### ISSUE TITLE
Release with ferm

### ISSUE THREAD

**Issue by margau** [MaxKellermann/ferm#74]
Hello,
as I need NAT64 with Jool for IPv6 Migration, I need ferm (as added in 392062953871e1ddce3e9a20cbfb096802db906d) to support this feature. Unfortunately, there is no official release tag yet with Jool support. This makes it difficult to use proper packages suitable for production usage.

Is there any roadmap, or help needed?
Thanks!

**Comment by nurupo** [comment]
2.6 just got released with JOOL & JOOL_SIIT support.

Sounds like this issue can be closed.
