### ISSUE TITLE
@if @eq($CHAIN, FORWARD) not working

### ISSUE THREAD

**Issue by basti12203** [MaxKellermann/ferm#77]
Hello, I try something like 
`@if @eq($CHAIN, FORWARD) proto udp dport 123 ACCEPT;`
But the rule is not applied.

`ferm -V`
`ferm 2.3`

**Comment by MaxKellermann** [comment]
Describe the symptom. Do you see a ferm error or does ferm silently omit the rule?
Also your sample omits necessary context. In which context do you write this rule?

**Comment by basti12203** [comment]
`@def $LOCAL_UDP = (domain);`
`domain (ip ip6) chain (INPUT FORWARD) {`
`        policy DROP;`
`  proto udp mod multiport destination-ports $LOCAL_UDP ACCEPT;`
` @if @eq($CHAIN, FORWARD) proto udp dport 123 ACCEPT;`
`}`

Ferm return no error. The rule is silently omit.
There are are some more rules but this above should illustrate it.

**Comment by MaxKellermann** [comment]
This works with ferm 2.5.2, but you're using a ferm version that's 4 years old.
