### ISSUE TITLE
problem with user-defined function

### ISSUE THREAD

**Issue by HugoFlorentino** [MaxKellermann/ferm#79]
I defined a function to humanize the hashlimit match:

```
@def &lim_src($name, $type, $rate, $burst, $expire, $destination) = {
	mod hashlimit
		hashlimit-mode srcip
		@if @eq($type, 'upto') hashlimit-upto $rate
		@if @eq($type, 'above') hashlimit-above $rate
		hashlimit-burst $burst
		hashlimit-htable-expire $expire
		hashlimit-name $name
	jump $destination;
}
```

I used it in the PREROUTING chain of the raw table, like this:

```
interface ! lo protocol tcp dport 443 mod tcp syn &lim_src(limit_https, above, 64kb/s, 1mb, 180000, MYCHAIN);
```

However when I tried to verify the resulting iptables rules with `ferm -nl file.conf`, no rule whatsoever was generated regarding hashlimit, and ferm produced no error either.

Is there anything invalid in the function?

**Comment by endreszabo** [comment]
it has worked for me this way:

```
@def &L($name, $type, $rate, $burst, $expire, $destination) = {
        jump $destination
        mod hashlimit
            hashlimit-mode srcip
            hashlimit-burst $burst
            hashlimit-htable-expire $expire
            hashlimit-name $name
        @if @eq($type, 'upto') {
            hashlimit-upto $rate;
        }
        @else {
            hashlimit-above $rate;
        }
}
table raw chain PREROUTING interface ! lo protocol tcp dport 443 mod tcp syn &L('limit_https', 'above', '64kb/s', '1mb', 180000, MYCHAIN);
table raw chain PREROUTING interface ! lo protocol tcp dport 443 mod tcp syn &L('limit_https', 'upto', '64kb/s', '1mb', 180000, MYCHAIN);
```

**Comment by HugoFlorentino** [comment]
> it has worked for me this way:
> 
>         @if @eq($type, 'upto') {
>             hashlimit-upto $rate;
>         }
>         @else {
>             hashlimit-above $rate;
>         }

This is not exaactly the same, someone might pass 'garbish' as a parameter and it would match 'hashlimit-above'. I tried with `@else @if(` but for some reason it didn't work for me.

**Comment by HugoFlorentino** [comment]
> 
> 
> it has worked for me this way:
> 
> ```
> @def &L($name, $type, $rate, $burst, $expire, $destination) = {
>         jump $destination
>         mod hashlimit
>             hashlimit-mode srcip
>             hashlimit-burst $burst
>             hashlimit-htable-expire $expire
>             hashlimit-name $name
>         @if @eq($type, 'upto') {
>             hashlimit-upto $rate;
>         }
>         @else {
>             hashlimit-above $rate;
>         }
> }
> table raw chain PREROUTING interface ! lo protocol tcp dport 443 mod tcp syn &L('limit_https', 'above', '64kb/s', '1mb', 180000, MYCHAIN);
> table raw chain PREROUTING interface ! lo protocol tcp dport 443 mod tcp syn &L('limit_https', 'upto', '64kb/s', '1mb', 180000, MYCHAIN);
> ```

BTW, Why does ferm fail if you move the jump line towards the end of the function? (which is the usual way to declare it in iptables)

**Comment by MaxKellermann** [comment]
You have two conflicting conditionals in your expression:
```
		@if @eq($type, 'upto') hashlimit-upto $rate
		@if @eq($type, 'above') hashlimit-above $rate
```
`$type` can't be both `upto` and `above`, so one of the two will always evaluate to false, making this rule always empty.
Note that `@if` doesn't apply to a line of ferm code, but to the whole rule.

**Comment by MaxKellermann** [comment]
> BTW, Why does ferm fail if you move the jump line towards the end of the function? (which is the usual way to declare it in iptables)

It doesn't, usually. But the way it's used here, the `jump` cannot be at the end, because the `}` closes the rule, just like a `;` does. This is a side effect of ferm's basic syntax when used with a curly braced block. Common stuff needs to be written before that block starts.
You can have the target at the end, but @endreszabo's rule has two ends: one in each block. Therefore, you'd need to copy the target into both blocks, duplicating code.
Further clarification: this syntax problem has nothing to do with targets; this applies to any part of a rule. You can't have additional rule pieces after the curly brace is closed, because the rule has ended already.

**Comment by MaxKellermann** [comment]
it

**Comment by HugoFlorentino** [comment]
> 
> 
> You have two conflicting conditionals in your expression:
> 
> ```
> 		@if @eq($type, 'upto') hashlimit-upto $rate
> 		@if @eq($type, 'above') hashlimit-above $rate
> ```
> 
> `$type` can't be both `upto` and `above`, so one of the two will always evaluate to false, making this rule always empty.
> Note that `@if` doesn't apply to a line of ferm code, but to the whole rule.

I thought the function parser would simply skip the non-matching condition and continue evaluating the rest (which is the typical behavior of an if function).

**Comment by MaxKellermann** [comment]
> I thought the function parser would simply skip the non-matching condition and continue evaluating the rest (which is the typical behavior of an if function).

True, it does! It skips the condition and thus the rest of the rule. That's how `@if` works!

**Comment by HugoFlorentino** [comment]
I was unaware that if had a final efect on the whole function and not just the local evaluation.

**Comment by HugoFlorentino** [comment]
> 
> 
> > BTW, Why does ferm fail if you move the jump line towards the end of the function? (which is the usual way to declare it in iptables)
> 
> It doesn't, usually. But the way it's used here, the `jump` cannot be at the end, because the `}` closes the rule, just like a `;` does. This is a side effect of ferm's basic syntax when used with a curly braced block. Common stuff needs to be written before that block starts.
> You can have the target at the end, but @endreszabo's rule has two ends: one in each block. Therefore, you'd need to copy the target into both blocks, duplicating code.
> Further clarification: this syntax problem has nothing to do with targets; this applies to any part of a rule. You can't have additional rule pieces after the curly brace is closed, because the rule has ended already.

One thin puzzles me though: his example even vaving two ends, did produce both iptables rules.

**Comment by MaxKellermann** [comment]
> I was unaware that if had a final efect on the whole function and not just the local evaluation.

I have no idea what that means.

> One thing puzzles me though: his example even having two ends, did produce both iptables rules

No, one function call only produced one rule. But there were two function calls.

**Comment by HugoFlorentino** [comment]
> No, one function call only produced one rule. But there were two function calls.

Yes, first call with type 'above' and it worked. If right curly braces marks the end of an user-defined function, it shouldn't have worked. Or could one do this: ?
```
[...]
  @if @eq($type, 'upto') {
    hashlimit-upto $rate;
  @else @if @eq($type, 'above') {
    hashlimit-above $rate;
  }
[...]
```

**Comment by MaxKellermann** [comment]
> If right curly braces marks the end of a user-defined function, it shouldn't have worked.

Again, I have no idea what you mean.

> Or could one do this: ?

You can do that.

**Comment by MaxKellermann** [comment]
btw. you don't need the curly braces. You need them only if you want to generate more than one rule in that branch. But it's ok to have unnecessary curly braces.

**Comment by HugoFlorentino** [comment]
> 
> 
> > If right curly braces marks the end of a user-defined function, it shouldn't have worked.
> 
> Again, I have no idea what you mean.
> 
> > Or could one do this: ?
> 
> You can do that.

I tried with his example, it didn't work.

**Comment by MaxKellermann** [comment]
Didn't work is the worst possible problem description.

**Comment by MaxKellermann** [comment]
If you have a problem with `@if` syntax and you believe it's a ferm bug, write a new bug report with all information on how to reproduce.

**Comment by HugoFlorentino** [comment]
```
@def &L($name, $type, $rate, $burst, $expire, $destination) = {
        jump $destination
        mod hashlimit
            hashlimit-mode srcip
            hashlimit-burst $burst
            hashlimit-htable-expire $expire
            hashlimit-name $name
        @if @eq($type, 'upto') {
            hashlimit-upto $rate;
        }
        @else @if @eq($type, 'upto') {
            hashlimit-above $rate;
        }
}

domain ip table raw {
  chain LOG_DROP {
    NFLOG nflog-prefix DROPPED;
    RETURN;
  }
  chain PREROUTING {
    policy ACCEPT;
    interface ! lo proto tcp
      mod tcp syn
      mod multiport destination-ports (80 443)
      &L(limit_nav, above, 128kb/minute, 1mb, 180000, LOG_DROP);
  }
}
```

The output from `ferm -nl` :

```
*raw
:LOG_DROP - [0:0]
:PREROUTING ACCEPT [0:0]
-A LOG_DROP --jump NFLOG --nflog-prefix DROPPED
-A LOG_DROP --jump RETURN
COMMIT
```

**Comment by MaxKellermann** [comment]
You still didn't describe a problem.

**Comment by HugoFlorentino** [comment]
sorry, a copy-paste problem:

```
*raw
:LOG_DROP - [0:0]
:PREROUTING ACCEPT [0:0]
-A LOG_DROP --jump NFLOG --nflog-prefix DROPPED
-A LOG_DROP --jump RETURN
-A PREROUTING ! --in-interface lo --protocol tcp --syn --match multiport --destination-ports 80,443 --jump LOG_DROP --match hashlimit --hashlimit-mode srcip --hashlimit-burst 1mb --hashlimit-htable-expire 180000 --hashlimit-name limit_nav --hashlimit-above 128kb/minute
COMMIT
```

**Comment by MaxKellermann** [comment]
And you *still* did not describe a problem.

**Comment by HugoFlorentino** [comment]
> 
> 
> And you _still_ did not describe a problem.

Are hashlimit conditions even evaluated after a `--jump` instruction?
