### ISSUE TITLE
"random-fully" not supported by import ferm 

### ISSUE THREAD

**Issue by palfrey** [MaxKellermann/ferm#80]
e.g. `-A POSTROUTING -s 10.42.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully`

The rule I think came from Kubernetes, so it's not directly of immediate interest, but did break import-ferm with `option 'random-fully' in line 113 not understood`

**Comment by palfrey** [comment]
:clap: That is a deeply impressive speed of bug fixing :)

**Comment by MaxKellermann** [comment]
Not a bug actually - ferm was missing support for this new iptables feature. As you see, adding support for new features is really simple, and anybody is welcome to submit micro-patches like that.
