### ISSUE TITLE
When service ferm is up, TCP connections are reset

### ISSUE THREAD

**Issue by julien-lecomte** [MaxKellermann/ferm#88]
This issue has puzzled me all day long, one to find it, but also to understand it.

Basically, when ferm status is active, and I am listening on a port, then I cannot `nc` nor `curl` to the port and I get a "Connection refused".

When ferm is inactive, I can connect to the port.

I've compared iptables, ebtanles, and sysctl before and after, and nothing shows why the TCP connection is reset.

This behavior only happens when I try to connect to something else than 127.0.0.1, or it's local IP 192.168.1.2:

Failure:

```
root@desktop:~# pkill -9 nc; service ferm restart ; iptables -F ; nc -l -p 8080 & sleep 1; curl -sS 82.64.XX.XX:8080
[1] 33177
curl: (7) Failed to connect to 82.64.60.13 port 8080: Connection refused
````

Success:

```
root@desktop:~# pkill -9 nc; service ferm stop ; iptables -F ; nc -l -p 8080 & sleep 1; curl -sS 82.64.XX.XX:8080
[1]+  Killed                  nc -l -p 8080
[1] 33230
GET / HTTP/1.1
Host: 82.64.60.13:8080
User-Agent: curl/7.74.0
Accept: */*

^C
```

The ferm rules are created by the [debops/debops ](https://github.com/debops/debops) and I have not modified them. After a lot of testing I figured it is caused by the file `005_rule_policy_filter_input.conf`. If I remove the file, I don't have the connection error any more.

```
root@desktop:/etc/ferm/rules.d# cat 005_rule_policy_filter_input.conf 
# Ansible managed

domain (ip ip6) table filter chain INPUT {
    policy DROP;
}
```

Nevertheless, I don't get it. I clear iptables, and the DROP policy is still in effect for my `nc` command.

I'm not high, I'm not drunk, I just can't find an explanation and this all seems like black magic because it makes no sense.

How can ferm be blocking connections if active but iptables is empty?

**Comment by MaxKellermann** [comment]
ferm cannot be "active" or "inactive". All it does is set up netfilter tables, and then it exits. Nothing remains of ferm after that, other than the netfilter tables modified by it. This part of your buig report confuses me enough that I cannot understand the problem.
