### ISSUE TITLE
IPv6:Port Syntax für DNAT

### ISSUE THREAD

**Issue by klaus-nicat** [MaxKellermann/ferm#97]
Hi! For IPv4 I write:
```
table nat {
        chain PREROUTING {
                proto tcp dport 5433 DNAT to 10.10.0.1:5432;
```

How di separate the port from the IP adress when using IPv6? I tried 
```
table nat {
        chain PREROUTING {
                proto tcp dport 5433 DNAT to [2a::ff]:5432;  # not accepted by ferm
```
table nat {
        chain PREROUTING {
                proto tcp dport 5433 DNAT to 2a::ff:5432;   # accepted by ferm, but dport is not changed to 5432
```

How does it work in ferm, or is IPv6 DNAT syntax just not supported?

**Comment by MaxKellermann** [comment]
You have to quote the parameter: `"[2a::ff]:5432"`
