### ISSUE TITLE
Feature Request: Preview of the iptables changes

### ISSUE THREAD

**Issue by 999faryad** [MaxKellermann/ferm#98]
It would be really nice if there was a parameter -p --preview, which would not make any changes to the system with --noexec, but would write the changes to the iptables rules to the stdout.

**Comment by MaxKellermann** [comment]
You mean like `--lines --noexec`?

**Comment by 999faryad** [comment]
Yes, similar, but unfortunately this only shows the rules that are applied, without the corresponding chains. 

I rather mean that the output would be like that of iptables -L

**Comment by MaxKellermann** [comment]
Not true. It does show chains, but it does *not* show the rules that are applied (nothing gets applied, which is the point of `--noexec`).

**Comment by 999faryad** [comment]
My usecase would be that I would like to use an iptables visualise tool to turn the IPTables rules into a graph/diagram without applying them.

Hence the suggestion that there would be an option to format the output like an output from iptables -L.

**Comment by MaxKellermann** [comment]
No. You better fix your "visualise tool" to accept a standard format and not the "iptables -L" output format, which is a pretty bad choice.
